[project]
name = "sillydream-banana"
description = "为 ComfyUI 引入 Google NanoBanana Gemini 文生图/图生图能力的自定义节点,提供批量生成、并发调度与余额监控等高级特性。"
version = "0.0.8"
license = { file = "LICENSE" }
dependencies = [
    "requests>=2.20.0",
]

[project.urls]
Repository = "https://github.com/qianchi7/ComfyUI-SillyDream-Banana"
"Bug Tracker" = "https://github.com/qianchi7/ComfyUI-SillyDream-Banana/issues"

[tool.comfy]
PublisherId = "qianchi7"
DisplayName = "Banana Gemini Image Generator"
includes = []
